In [2]:
import __main__
print(__main__.__package__)

None


In [3]:
import sys
import os

sys.path.append(os.path.abspath("..")) 

In [4]:
# testing for multihead attention
from transformer.config.multihead_attention import MultiHeadAttentionConfig

multi_attn_conf = MultiHeadAttentionConfig(
    embed_dim=2, # size of vector for each token
    num_head=1,
    dropout=0.3
)

In [5]:
import torch

torch.manual_seed(42)

# check with 1 batch, 1 token, 2 embed dim
query = torch.randn(1, 1, 2)
key = torch.randn(1, 1, 2)
value = torch.randn(1, 1, 2)

In [6]:
print(f"Query: {query}")
print(f"Key: {key}")
print(f"Value: {value}")

Query: tensor([[[0.3367, 0.1288]]])
Key: tensor([[[0.2345, 0.2303]]])
Value: tensor([[[-1.1229, -0.1863]]])


In [7]:
from transformer.base.multihead_attention import MultiHeadAttention

multi_attn = MultiHeadAttention(multi_attn_conf)

In [8]:
x = torch.randn(2, 3)
x

tensor([[-0.7658, -0.7506,  1.3525],
        [ 0.6863, -0.3278,  0.7950]])

In [9]:
torch.transpose(x, -2, -1)

tensor([[-0.7658,  0.6863],
        [-0.7506, -0.3278],
        [ 1.3525,  0.7950]])

In [10]:
x = torch.Tensor([
    [
        [1.87, 1.09],
        [-1.68, 0.67]
    ]
])

In [11]:
multi_attn(x, x, x)

Linear Projection
Query: tensor([[[ 1.6264,  0.6333],
         [-0.2684, -0.5352]]], grad_fn=<ViewBackward0>)
Query Shape: torch.Size([1, 2, 2])
Key: tensor([[[-0.7080, -0.2305],
         [ 0.3881,  0.9608]]], grad_fn=<ViewBackward0>)
Key Shape: torch.Size([1, 2, 2])
Value: tensor([[[-1.3324, -1.5352],
         [ 0.7861, -0.6478]]], grad_fn=<ViewBackward0>)
Value Shape: torch.Size([1, 2, 2])
Split Num Head
Query: tensor([[[[ 1.6264,  0.6333],
          [-0.2684, -0.5352]]]], grad_fn=<TransposeBackward0>)
Query Shape: torch.Size([1, 1, 2, 2])
Key: tensor([[[[-0.7080, -0.2305],
          [ 0.3881,  0.9608]]]], grad_fn=<TransposeBackward0>)
Key Shape: torch.Size([1, 1, 2, 2])
Value: tensor([[[[-1.3324, -1.5352],
          [ 0.7861, -0.6478]]]], grad_fn=<TransposeBackward0>)
Value Shape: torch.Size([1, 1, 2, 2])
Scaled Dot Products
K transpose: tensor([[[[-0.7080,  0.3881],
          [-0.2305,  0.9608]]]], grad_fn=<TransposeBackward0>)
Head dimension: 2
Attention score: tensor([[[[-0.9175,

tensor([[[0.8764, 0.6843],
         [0.2045, 0.6089]]], grad_fn=<ViewBackward0>)